# Introduction

# Part 1: Creating a Class

Create spark session and import spark_data_check module

In [1]:
from pyspark.sql import SparkSession
spark = SparkSession.builder.appName('my_app').config("spark.sql.ansi.enabled", "false").getOrCreate()

from pyspark.sql import functions as F
from spark_data_check import SparkDataCheck

WARNING: Using incubator modules: jdk.incubator.vector
Using Spark's default log4j profile: org/apache/spark/log4j2-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
26/03/26 17:21:28 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
26/03/26 17:21:29 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
26/03/26 17:21:29 WARN Utils: Service 'SparkUI' could not bind on port 4041. Attempting port 4042.
26/03/26 17:21:29 WARN Utils: Service 'SparkUI' could not bind on port 4042. Attempting port 4043.
26/03/26 17:21:29 WARN Utils: Service 'SparkUI' could not bind on port 4043. Attempting port 4044.

### Class Method: read_csv()

The read_csv() class method uses spark.read.load() to create an instance of the SparkDataCheck class while reading in a csv. We will use it to create an instance of SparkDataCheck and read in the air.csv file.

In [2]:
air = SparkDataCheck.read_csv(spark, file_path = 'air.csv')

# drop extra index column
air.df = air.df.drop("_c0")

# replace periods in column names with underscores to avoid errors
new_cols = [c.replace(".", "_") for c in air.df.columns]
air.df = air.df.toDF(*new_cols)

# show first 5 rows of data frame
air.df.show(5)

+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+
|     Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+
|3/10/2004|2026-03-26 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578|
|3/10/2004|2026-03-26 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255|
|3/10/2004|2026-03-26 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502|
|3/10/2004|2026-03-26 21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867|
|3/10/2004|2026-03-26 22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888|
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+
only showing top 5 rows

Print air data schema to look at column names and types

In [34]:
air.df.printSchema()

root
 |-- _c0: integer (nullable = true)
 |-- Date: string (nullable = true)
 |-- Time: timestamp (nullable = true)
 |-- CO(GT): double (nullable = true)
 |-- PT08.S1(CO): integer (nullable = true)
 |-- NMHC(GT): integer (nullable = true)
 |-- C6H6(GT): double (nullable = true)
 |-- PT08.S2(NMHC): integer (nullable = true)
 |-- NOx(GT): integer (nullable = true)
 |-- PT08.S3(NOx): integer (nullable = true)
 |-- NO2(GT): integer (nullable = true)
 |-- PT08.S4(NO2): integer (nullable = true)
 |-- PT08.S5(O3): integer (nullable = true)
 |-- T: double (nullable = true)
 |-- RH: double (nullable = true)
 |-- AH: double (nullable = true)

Now that we have read in the data, we can use it to test each of the methods in the SparkDataCheck class. 

### Method: check_numeric_col()

For the first method, check_numeric_col(), we will first test it by providing 'CO(GT)' as the numeric column.

The function has worked as intended in this case, we can see all of the values were correctly assigned 'true' or 'false' based on whether they are between the provided bounds.

In [14]:
air.check_numeric_col(column = 'CO(GT)', lower = 0, upper = 10)
air.df.select('CO(GT)', 'within_num_range').show()

+------+----------------+
|CO(GT)|within_num_range|
+------+----------------+
|   2.6|            true|
|   2.0|            true|
|   2.2|            true|
|   2.2|            true|
|   1.6|            true|
|   1.2|            true|
|   1.2|            true|
|   1.0|            true|
|   0.9|            true|
|   0.6|            true|
|-200.0|           false|
|   0.7|            true|
|   0.7|            true|
|   1.1|            true|
|   2.0|            true|
|   2.2|            true|
|   1.7|            true|
|   1.5|            true|
|   1.6|            true|
|   1.9|            true|
+------+----------------+
only showing top 20 rows

Now we will test that the error messages work properly.

First, try providing no bounds. We will test the method on the numeric column 'T' this time.

The result is as expected, with an error message being printed saying to provide at least one bound.

In [15]:
air.check_numeric_col(column = 'T')

Error: Must provide at least one of 'upper' or 'lower'

Now we will test the method by only providing one bound.

This test worked as expected, with the column only being compared to the provided lower bound.

In [20]:
air.check_numeric_col(column = 'T', lower = 10)
air.df.select('T', 'within_num_range').show()

+----+----------------+
|   T|within_num_range|
+----+----------------+
|13.6|            true|
|13.3|            true|
|11.9|            true|
|11.0|            true|
|11.2|            true|
|11.2|            true|
|11.3|            true|
|10.7|            true|
|10.7|            true|
|10.3|            true|
|10.1|            true|
|11.0|            true|
|10.5|            true|
|10.2|            true|
|10.8|            true|
|10.5|            true|
|10.8|            true|
|10.5|            true|
| 9.5|           false|
| 8.3|           false|
+----+----------------+
only showing top 20 rows

Lastly, we will test the method by providing a non-numeric column. The 'Time' column is a timestamp, so we will use it for this test.

The result is as expected, with an error message printing telling us to provide a numeric column.

In [12]:
air.check_numeric_col(column = 'Time', lower = 0, upper = 10)

Error: Column must of type float, int, longint, bigint, double, or integer

### Method: check_string_col

Now we will test the method check_string_col(). This method accepts a column name and a set of levels and returns a data frame with a column added indicating whether the values of the column are within the user specified levels. 

First, we will test the method using the 'Date' column, which is a string.

The result is as expected - a boolean column called 'within_level' was added and we can see that the values of within_level are correct.

In [17]:
air.check_string_col(column = 'Date', levels = ['3/10/2004', '3/11/2004'])
air.df.select('Date', 'within_level').show()

+---------+------------+
|     Date|within_level|
+---------+------------+
|3/10/2004|        true|
|3/10/2004|        true|
|3/10/2004|        true|
|3/10/2004|        true|
|3/10/2004|        true|
|3/10/2004|        true|
|3/11/2004|        true|
|3/11/2004|        true|
|3/11/2004|        true|
|3/11/2004|        true|
|3/11/2004|        true|
|3/11/2004|        true|
|3/11/2004|        true|
|3/11/2004|        true|
|3/11/2004|        true|
|3/11/2004|        true|
|3/11/2004|        true|
|3/11/2004|        true|
|3/11/2004|        true|
|3/11/2004|        true|
+---------+------------+
only showing top 20 rows

Now let's see what we get when we provide levels that are not in the provided column.

All of the 'within_level' values are false, so the method worked correctly.

In [18]:
air.check_string_col(column = 'Date', levels = ['0', '1', '2'])
air.df.select('Date', 'within_level').show()

+---------+------------+
|     Date|within_level|
+---------+------------+
|3/10/2004|       false|
|3/10/2004|       false|
|3/10/2004|       false|
|3/10/2004|       false|
|3/10/2004|       false|
|3/10/2004|       false|
|3/11/2004|       false|
|3/11/2004|       false|
|3/11/2004|       false|
|3/11/2004|       false|
|3/11/2004|       false|
|3/11/2004|       false|
|3/11/2004|       false|
|3/11/2004|       false|
|3/11/2004|       false|
|3/11/2004|       false|
|3/11/2004|       false|
|3/11/2004|       false|
|3/11/2004|       false|
|3/11/2004|       false|
+---------+------------+
only showing top 20 rows

Next we can test the method by providing a level that is in the Date column and a level that is not in the date column.

All of the rows where Date = '3/10/2004' are true for the within_level column and all of the other rows are false for within_level, so this worked correctly.

In [19]:
air.check_string_col(column = 'Date', levels = ['3/10/2004', '1'])
air.df.select('Date', 'within_level').show()

+---------+------------+
|     Date|within_level|
+---------+------------+
|3/10/2004|        true|
|3/10/2004|        true|
|3/10/2004|        true|
|3/10/2004|        true|
|3/10/2004|        true|
|3/10/2004|        true|
|3/11/2004|       false|
|3/11/2004|       false|
|3/11/2004|       false|
|3/11/2004|       false|
|3/11/2004|       false|
|3/11/2004|       false|
|3/11/2004|       false|
|3/11/2004|       false|
|3/11/2004|       false|
|3/11/2004|       false|
|3/11/2004|       false|
|3/11/2004|       false|
|3/11/2004|       false|
|3/11/2004|       false|
+---------+------------+
only showing top 20 rows

Lastly, we will test the method by providing a non-string column to the function.

This correctly returned an error message stating that the provided column must be a string column.

In [9]:
air.check_string_col(column = 'T', levels = [1, 2, 3])

Error: Column type must be string.

### Method: check_missing_values()

Next, we wil test the check_missing_values() method. This method checks a column for missing values and returns the modified data frame with a boolean column indicating whether the values in a column are missing. 

Let's first test the function on a numeric column. 

The 'is_missing' column was added properly and correctly show that none of these values of 'AH' are missing.

In [ ]:
air.check_missing_values(column = 'AH')
air.df.select('AH', 'is_missing').show()

Let's now test this method on a different type of column. We will test it on the 'Time' column, which is a timestamp.

Again, the result is as expected- none of the values are missing and all of the 'is_missing' values say false.

In [ ]:
air.check_missing_values(column = 'Time')
air.df.select('Time', 'is_missing').show()

In order to confirm this method works as intended, we want to test it on a column that has null values. Let's check the number of null values in each column to see which column we can test this method on.

In [ ]:
air.df.select([
    F.sum(F.when(F.col(f"`{c}`").isNull(), 1).otherwise(0)).alias(c)
    for c in air.df.columns
]).show()

Currently, none of the columns have null values, so we can't confirm that the method correctly identifies null values. 

However, we know from the first project that the variables 'C6H6(GT)' and 'CO(GT)' contains missing values, which are coded as '-200'. We can reassign these values as nulls and then test our check_missing_values() method. 

Then we can rerun the code to check the number of missing values per column to make sure this worked.

CO(GT) now has 1683 missing values and C6H6(GT) has 366 missing values, so we can test our method on these columns.

In [ ]:
# columns to reassign values to missing for
cols = ['CO(GT)', 'C6H6(GT)']

# replace values for both columns
for col in cols:
    air.df = air.df.withColumn(
        col,
        F.when(F.col(col) == -200, None).otherwise(F.col(col))
    )

# get null value counts after replacing values
air.df.select([
    F.sum(F.when(F.col(c).isNull(), 1).otherwise(0)).alias(c)
    for c in air.df.columns
]).show()

Now we can test the method on these two columns. 

In this output, there is one null value for CO(GT), and we can see that check_missing_values correctly assigned 'false' to this row.

In [ ]:
air.check_missing_values(column = 'CO(GT)')
air.df.select('CO(GT)', 'is_missing').show()

Now let's test the method on C6H6(GT).

This time, we will return the count of true and false values from the 'is_missing' column to make sure the number of true values aligns with the number of nulls in 'C6H6(GT)'. 

This returned 366, which is the same number of null values in the column.

In [ ]:
air.check_missing_values(column = 'C6H6(GT)')
air.df.select('C6H6(GT)', 'is_missing').groupby('is_missing').count().show()

### Method: summarize_min_max()

This method takes in a numeric column and reports the minimum and maximum values of the column. A grouping column can optionally be provided. If no column name is provided, all numeric columns will be summarized.

First, let's test the method using a numeric column with no grouping column.

The output is a pandas data frame with 'CO(GT)_min' and 'CO(GT)_max' columns, as expected.

In [7]:
air.summarize_min_max(column = 'CO(GT)')

   CO(GT)_min  CO(GT)_max
0         0.1        11.9

Now lets test the method using 'Date' as the grouping column and 'C6H6(GT)' as the numeric column to summarize.

I used sort_values() to sort the result by the Date column to make it easier to read.

This returned the minimum and maximum values of 'C6H6(GT)' for each value of 'Date' as expected.

In [8]:
air.summarize_min_max(column = 'C6H6(GT)', group_col = 'Date').sort_values('Date')

          Date  C6H6(GT)_max  C6H6(GT)_max
350   1/1/2005           3.0          16.6
308  1/10/2005           1.3          21.4
117  1/11/2005           2.1          26.5
36   1/12/2005           4.2          28.4
253  1/13/2005           3.2          26.6
..         ...           ...           ...
172   9/5/2004           1.9          30.3
39    9/6/2004           1.0          13.5
382   9/7/2004           2.7          22.0
131   9/8/2004          10.6          34.5
322   9/9/2004           2.3          32.3

[391 rows x 3 columns]

Now let's try passing no numeric column and no grouping column to the method. It should find all numeric columns in the data frame and find the minimum and maximum values for each one.

In [ ]:
air.summarize_min_max()

Next, we can try passing a column to group by, but no numeric column. The method should find all numeric columns in the data frame and summarize the minimum and maximum values of each, grouped by the given grouping column. We will again use 'Date' as the grouping column.

In [ ]:
air.summarize_min_max(group_col = 'Date').sort_values('Date')

### Method: get_value_counts()

The get_value_counts() method takes in one or two string columns and gets the counts. If one column is provided, it will count the number of instances of each value of the column. If two columns are provided, it will report the counts for each combination of the two columns.

Since the air data frame only has one string column, 'Date', we need to make a few more so that we can properly test this method.

We will split the date column into three parts to get a day column, month column, and year column.

In [ ]:
air.df = (
    air.df
    .withColumn('Month', F.split(F.col('Date'), '/').getItem(0))
    .withColumn('Day',   F.split(F.col('Date'), '/').getItem(1))
    .withColumn('Year',  F.split(F.col('Date'), '/').getItem(2))
)
air.df.show(5)

Now we need to test the get_value_counts() method. First we will test it using just one string column.

From the output we can see that the method correctly reported the number of observations for each value of 'Date'.

In [ ]:
air.get_value_counts(column1 = 'Date')

Now let's try providing two columns to the method. We will use 'Month' as column 1 and 'Year' as column 2. The result should be a data frame containing the number of instances of each combination of 'Month' and 'Year'

In [ ]:
air.get_value_counts(column1 = 'Month', column2 = 'Year')

Next we can try passing a numeric column to the method.

This correctly resulted in an error stating that the column must be numeric.

In [ ]:
air.get_value_counts(column1 = 'T')

Now, we will make sure we get an error if we try to pass a numeric column to the 'column2' argument. Let's test the method using 'Month' for the first column and 'T' for the second column.

This correctly output an error stating that the columns need to be numeric.

In [ ]:
air.get_value_counts(column1 = 'Month', column2 = 'T')

### Class Method: read_pandas()

The read_pandas() method creates an instance of the SparkDataCheck class from a pandas data frame.

Let's read in air.csv with pandas and then use our method to create an instance of SparkDataCheck.

In [ ]:
import pandas as pd

# read in air.csv with pandas
pandas_df = pd.read_csv('air.csv', index_col = 0)

# use method to create instance of class
air_pd = SparkDataCheck.read_pandas(spark, pandas_df)

Let's use one of our methods on this data frame. We will test the 'check_numeric_col()' method using the 'CO(GT)' column.

In [ ]:
air_pd.check_numeric_col('CO(GT)', lower = 0, upper = 10)
air_pd.df.select('CO(GT)', 'within_num_range').show()

# Part 2: NFL Data Analysis

For part 2, we will do some analysis on weekly NFL data using Spark SQL and pandas-on-spark.

We will start by doing the analysis using only pandas-on-spark. 

First, we need to import some packages and read in the data set.

In [2]:
import pyspark.pandas as ps

ps.set_option('compute.fail_on_ansi_mode', False)
import warnings
from pyspark.pandas.utils import PandasAPIOnSparkAdviceWarning
warnings.simplefilter("ignore", category=PandasAPIOnSparkAdviceWarning)

Read in the weekly NFL data using PySpark and look at the first 5 rows

In [3]:
nfl = ps.read_csv("weekly_nfl_data.csv")
nfl.head()

26/03/26 19:39:39 WARN SparkStringUtils: Truncated the string representation of a plan since it was too large. This behavior can be adjusted by setting 'spark.sql.debug.maxToStringFields'.

    player_id player_name    player_display_name position position_group headshot_url recent_team  season  week season_type opponent_team  completions  attempts  passing_yards  passing_tds  interceptions  sacks  sack_yards  sack_fumbles  sack_fumbles_lost  passing_air_yards  passing_yards_after_catch  passing_first_downs  passing_epa  passing_2pt_conversions  pacr  dakota  carries  rushing_yards  rushing_tds  rushing_fumbles  rushing_fumbles_lost  rushing_first_downs  rushing_epa  rushing_2pt_conversions  receptions  targets  receiving_yards  receiving_tds  receiving_fumbles  receiving_fumbles_lost  receiving_air_yards  receiving_yards_after_catch  receiving_first_downs  receiving_epa  receiving_2pt_conversions  racr  target_share  air_yards_share  wopr  special_teams_tds  fantasy_points  fantasy_points_ppr
0  00-0000003        None  Abdul-Karim al-Jabbar       RB             RB         None         MIA    1999     1         REG           DEN            0         0            0.0            0            0.0    0.0         0.0             0                  0                0.0                        0.0                  0.0          NaN                        0   NaN     NaN       16           60.0            1              0.0                   0.0                  4.0     6.248771                        0           1        1              7.0              0                0.0                     0.0                  0.0                          0.0                    0.0       0.292378                          0   0.0      0.052632              NaN   NaN                0.0            12.7                13.7
1  00-0000003        None  Abdul-Karim al-Jabbar       RB             RB         None         MIA    1999     2         REG           ARI            0         0            0.0            0            0.0    0.0         0.0             0                  0                0.0                        0.0                  0.0          NaN                        0   NaN     NaN        9           33.0            0              0.0                   0.0                  1.0    -1.434950                        0           3        4             18.0              0                0.0                     0.0                  0.0                          0.0                    1.0       0.377009                          0   0.0      0.117647              NaN   NaN                0.0             5.1                 8.1
2  00-0000003        None  Abdul-Karim al-Jabbar       RB             RB         None         MIA    1999     4         REG           BUF            0         0            0.0            0            0.0    0.0         0.0             0                  0                0.0                        0.0                  0.0          NaN                        0   NaN     NaN        3            2.0            0              0.0                   0.0                  0.0    -1.539952                        0           0        1              0.0              0                0.0                     0.0                  0.0                          0.0                    0.0      -0.699578                          0   NaN      0.023810              NaN   NaN                0.0             0.2                 0.2
3  00-0000003        None  Abdul-Karim al-Jabbar       RB             RB         None         CLE    1999     7         REG            LA            0         0            0.0            0            0.0    0.0         0.0             0                  0                0.0                        0.0                  0.0          NaN                        0   NaN     NaN        6           27.0            0              0.0                   0.0                  0.0     0.216051                        0           2        2              8.0              0                0.0                     0.0                  0.0                          0.0                    0.0      -0.228454                          0   0.0      0.050000              NaN   NaN                0.0             3.5                 5.5
4  00-0000003        None  Abdul-Karim al-Jabbar       RB             RB         None         CLE    1999     8         REG            NO            0         0            0.0            0            0.0    0.0         0.0             0                  0                0.0                        0.0                  0.0          NaN                        0   NaN     NaN       13           39.0            0              0.0                   0.0                  2.0    -2.972259                        0           0        0              0.0              0                0.0                     0.0                  0.0                          0.0                    0.0            NaN                          0   NaN           NaN              NaN   NaN                0.0             3.9                 3.9

Let's look at the column names in the data frame.

In [4]:
nfl.columns.tolist()

['player_id',
 'player_name',
 'player_display_name',
 'position',
 'position_group',
 'headshot_url',
 'recent_team',
 'season',
 'week',
 'season_type',
 'opponent_team',
 'completions',
 'attempts',
 'passing_yards',
 'passing_tds',
 'interceptions',
 'sacks',
 'sack_yards',
 'sack_fumbles',
 'sack_fumbles_lost',
 'passing_air_yards',
 'passing_yards_after_catch',
 'passing_first_downs',
 'passing_epa',
 'passing_2pt_conversions',
 'pacr',
 'dakota',
 'carries',
 'rushing_yards',
 'rushing_tds',
 'rushing_fumbles',
 'rushing_fumbles_lost',
 'rushing_first_downs',
 'rushing_epa',
 'rushing_2pt_conversions',
 'receptions',
 'targets',
 'receiving_yards',
 'receiving_tds',
 'receiving_fumbles',
 'receiving_fumbles_lost',
 'receiving_air_yards',
 'receiving_yards_after_catch',
 'receiving_first_downs',
 'receiving_epa',
 'receiving_2pt_conversions',
 'racr',
 'target_share',
 'air_yards_share',
 'wopr',
 'special_teams_tds',
 'fantasy_points',
 'fantasy_points_ppr']

We are only interested in seasons 2005 to 2023, the position 'QB', and the regular season. Let's filter the data accordingly.

In [5]:
nfl_subset = nfl[
    (nfl["position"] == "QB") &
    (nfl["season_type"] == "REG") &
    (nfl["season"].between(2005, 2023))
]

# look at the first few rows of data after subsetting
nfl_subset.head(3)

        player_id player_name player_display_name position position_group headshot_url recent_team  season  week season_type opponent_team  completions  attempts  passing_yards  passing_tds  interceptions  sacks  sack_yards  sack_fumbles  sack_fumbles_lost  passing_air_yards  passing_yards_after_catch  passing_first_downs  passing_epa  passing_2pt_conversions  pacr    dakota  carries  rushing_yards  rushing_tds  rushing_fumbles  rushing_fumbles_lost  rushing_first_downs  rushing_epa  rushing_2pt_conversions  receptions  targets  receiving_yards  receiving_tds  receiving_fumbles  receiving_fumbles_lost  receiving_air_yards  receiving_yards_after_catch  receiving_first_downs  receiving_epa  receiving_2pt_conversions  racr  target_share  air_yards_share  wopr  special_teams_tds  fantasy_points  fantasy_points_ppr
29406  00-0000722        None          Tony Banks       QB             QB         None         HOU    2005    17         REG            SF           14        25          173.0            1            2.0    0.0        -0.0             0                  0                0.0                        0.0                  7.0    -3.693779                        0   0.0  0.032036        2           -2.0            0              0.0                   0.0                  0.0     0.000000                        0           0        0              0.0              0                0.0                     0.0                  0.0                          0.0                    0.0            NaN                          0   NaN           NaN              NaN   NaN                0.0            6.72                6.72
29426  00-0000865        None       Charlie Batch       QB             QB         None         PIT    2005     9         REG            GB            9        16           65.0            0            1.0    1.0         6.0             1                  0                0.0                        0.0                  4.0    -6.609788                        0   0.0  0.025249        8           14.0            0              0.0                   0.0                  1.0    -1.614163                        0           0        0              0.0              0                0.0                     0.0                  0.0                          0.0                    0.0            NaN                          0   NaN           NaN              NaN   NaN                0.0            2.00                2.00
29427  00-0000865        None       Charlie Batch       QB             QB         None         PIT    2005    10         REG           CLE           13        19          150.0            0            0.0    0.0        -0.0             0                  0                0.0                        0.0                  7.0     5.193222                        0   0.0  0.171917        3           16.0            1              0.0                   0.0                  2.0     0.737467                        0           0        0              0.0              0                0.0                     0.0                  0.0                          0.0                    0.0            NaN                          0   NaN           NaN              NaN   NaN                0.0           13.60               13.60

We are only interested in the columns player_display_name, season, week, completions, attempts, passing?_yards, passing_tds, and interceptions, so we will subset the nfl_subset dataframe to only include these columns.

In [6]:
nfl_subset = nfl_subset[
    [
        "player_display_name",
        "season",
        "week",
        "completions",
        "attempts",
        "passing_yards",
        "passing_tds",
        "interceptions"
    ]
]

# look at the first few rows of data after subsetting
nfl_subset.head(3)

      player_display_name  season  week  completions  attempts  passing_yards  passing_tds  interceptions
29406          Tony Banks    2005    17           14        25          173.0            1            2.0
29426       Charlie Batch    2005     9            9        16           65.0            0            1.0
29427       Charlie Batch    2005    10           13        19          150.0            0            0.0

Now we want to find the sum of the week, completions, attempts, passing_yards, passing_tds, and interceptions columns for each player and season combination. To do this, we will group by player and season and use .agg() to calculate the metrics for the remaining columns.

In [7]:
nfl_summary = (
    # group by player and season
    nfl_subset.groupby(["player_display_name", "season"])
      # compute sum and mean of remaining columns
      .agg({
          "completions": ["sum", "mean"],
          "attempts": ["sum", "mean"],
          "passing_yards": ["sum", "mean"],
          "passing_tds": ["sum", "mean"],
          "interceptions": ["sum", "mean"]
      })
)

# look at the first few rows of the summarized data
nfl_summary.head(3)

                           completions            attempts            passing_yards             passing_tds           interceptions
                                   sum       mean      sum       mean           sum        mean         sum      mean           sum      mean
player_display_name season
Jake Delhomme       2006           263  20.230769      431  33.153846        2805.0  215.769231          17  1.307692          11.0  0.846154
Jake Plummer        2005           277  17.312500      456  28.500000        3366.0  210.375000          18  1.125000           7.0  0.437500
Matt Schaub         2006            18   3.600000       27   5.400000         208.0   41.600000           1  0.200000           2.0  0.400000

Next we want to create two new variables using this summarized data:
- completion_percentage = (sum of completions)/(sum of attempts)
- td_int_ratio = (sum passing tds)/(sum interceptions)

Before we can do this, we need to flatten the summarized data frame to get rid of the multilevel columns. We also need to turn the player and season columns into regular columns rather than index levels.

In [8]:
# rename columns to include the original column name and the metric
nfl_summary.columns = [
    f"{col[0]}_{col[1]}" for col in nfl_summary.columns
]

# turn player and season into regular columns instead of index
nfl_summary = nfl_summary.reset_index()
nfl_summary.head(3)

  player_display_name  season  completions_sum  completions_mean  attempts_sum  attempts_mean  passing_yards_sum  passing_yards_mean  passing_tds_sum  passing_tds_mean  interceptions_sum  interceptions_mean
0       Jake Delhomme    2006              263         20.230769           431      33.153846             2805.0          215.769231               17          1.307692               11.0            0.846154
1        Jake Plummer    2005              277         17.312500           456      28.500000             3366.0          210.375000               18          1.125000                7.0            0.437500
2         Matt Schaub    2006               18          3.600000            27       5.400000              208.0           41.600000                1          0.200000                2.0            0.400000

Now that we have flattened the data frame, we can compute our new variables.

First we will calculate completion percentage.

The completion percentage calculation uses the column 'attempts_sum' as the denominator and the td_int_ratio calculation uses the column 'interceptions_sum' as the denominator. Both of these columns have zero values, so we need to replace those with null values to avoid getting an error due to trying to divide by zero.

In [17]:
# calculate completion percentage
nfl_summary["completion_percentage"] = (
    nfl_summary["completions_sum"] / nfl_summary["attempts_sum"]
)

# replace values of 0 for interceptions_sum with None to avoid divide by zero error
nfl_summary[["attempts_sum", "interceptions_sum"]] = nfl_summary[["attempts_sum", "interceptions_sum"]].replace(0, None)

# calculate td_int_ratio
nfl_summary["td_int_ratio"] = (
    nfl_summary["passing_tds_sum"] / nfl_summary["interceptions_sum"]
)

nfl_result = nfl_summary

# view the first few rows of the result data frame
nfl_result.head()

/opt/tljh/user/envs/pySpark3/lib/python3.9/site-packages/pyspark/pandas/frame.py:6420: FutureWarning: DataFrame.replace without 'value' and with non-dict-like 'to_replace' is deprecated and will raise in a future version. Explicitly specify the new values instead.
  warnings.warn(

  player_display_name  season  completions_sum  completions_mean  attempts_sum  attempts_mean  passing_yards_sum  passing_yards_mean  passing_tds_sum  passing_tds_mean  interceptions_sum  interceptions_mean  completion_percentage  td_int_ratio
0       Jake Delhomme    2006              263         20.230769           431      33.153846             2805.0          215.769231               17          1.307692               11.0            0.846154               0.610209      1.545455
1        Jake Plummer    2005              277         17.312500           456      28.500000             3366.0          210.375000               18          1.125000                7.0            0.437500               0.607456      2.571429
2         Matt Schaub    2006               18          3.600000            27       5.400000              208.0           41.600000                1          0.200000                2.0            0.400000               0.666667      0.500000
3         Vince Young    2006              184         12.266667           356      23.733333             2199.0          146.600000               12          0.800000               13.0            0.866667               0.516854      0.923077
4       Kerry Collins    2007               50          8.333333            82      13.666667              531.0           88.500000                0          0.000000                NaN            0.000000               0.609756           NaN

Now that we have these metrics and calculated variables, we want to do some more subsetting.

Let's start by finding the player/season combinations where the sum of attempts is at least 50.

In [24]:
nfl_result[nfl_result["attempts_sum"] >= 50]

           player_display_name  season  completions_sum  completions_mean  attempts_sum  attempts_mean  passing_yards_sum  passing_yards_mean  passing_tds_sum  passing_tds_mean  interceptions_sum  interceptions_mean  completion_percentage  td_int_ratio
0                Jake Delhomme    2006              263         20.230769           431      33.153846             2805.0          215.769231               17          1.307692               11.0            0.846154               0.610209      1.545455
1                 Jake Plummer    2005              277         17.312500           456      28.500000             3366.0          210.375000               18          1.125000                7.0            0.437500               0.607456      2.571429
3                  Vince Young    2006              184         12.266667           356      23.733333             2199.0          146.600000               12          0.800000               13.0            0.866667               0.516854      0.923077
4                Kerry Collins    2007               50          8.333333            82      13.666667              531.0           88.500000                0          0.000000                NaN            0.000000               0.609756           NaN
6                Charlie Batch    2006               30          4.285714            52       7.428571              477.0           68.142857                5          0.714286                NaN            0.000000               0.576923           NaN
7                  Eli Manning    2006              301         18.812500           522      32.625000             3244.0          202.750000               25          1.562500               18.0            1.125000               0.576628      1.388889
9                 Mark Brunell    2006              162         16.200000           261      26.100000             1789.0          178.900000                8          0.800000                4.0            0.400000               0.620690      2.000000
10                  Shaun Hill    2007               54         18.000000            80      26.666667              501.0          167.000000                5          1.666667                2.0            0.666667               0.675000      2.500000
11                Aaron Brooks    2006              110         13.750000           192      24.000000             1105.0          138.125000                3          0.375000                8.0            1.000000               0.572917      0.375000
12                 Brett Favre    2006              343         21.437500           613      38.312500             3885.0          242.812500               18          1.125000               18.0            1.125000               0.559543      1.000000
13                  Drew Brees    2007              443         27.687500           655      40.937500             4428.0          276.750000               28          1.750000               18.0            1.125000               0.676336      1.555556
14            Bruce Gradkowski    2006              177         13.615385           328      25.230769             1661.0          127.769231                9          0.692308                9.0            0.692308               0.539634      1.000000
15             Matt Hasselbeck    2005              294         18.375000           450      28.125000             3455.0          215.937500               24          1.500000               10.0            0.625000               0.653333      2.400000
18                Tommy Maddox    2005               34         11.333333            71      23.666667              406.0          135.333333                2          0.666667                4.0            1.333333               0.478873      0.500000
20               Jake Delhomme    2007               55         18.333333            86      28.666667              617.0          205.666667                8          2.666667                1.0            0.333333               0.639535      8.000000
21                Mark Brunell    2005              262         16.375000           454      28.375000             3050.0          190.625000               23          1.437500               10.0            0.625000               0.577093      2.300000
22                 Marc Bulger    2007              221         18.416667           378      31.500000             2392.0          199.333333               11          0.916667               15.0            1.250000               0.584656      0.733333
23               David Garrard    2007              208         17.333333           325      27.083333             2509.0          209.083333               18          1.500000                3.0            0.250000               0.640000      6.000000
24                 Kurt Warner    2005              242         24.200000           375      37.500000             2713.0          271.300000               11          1.100000                9.0            0.900000               0.645333      1.222222
25               Kelly Holcomb    2007               42         14.000000            83      27.666667              511.0          170.333333                2          0.666667                1.0            0.333333               0.506024      2.000000
26                 Matt Schaub    2005               33          4.714286            64       9.142857              495.0           70.714286                4          0.571429                NaN            0.000000               0.515625           NaN
27            Vinny Testaverde    2005               60         10.000000           106      17.666667              777.0          129.500000                1          0.166667                6.0            1.000000               0.566038      0.166667
30            Brooks Bollinger    2007               33          6.600000            50      10.000000              391.0           78.200000                1          0.200000                1.0            0.200000               0.660000      1.000000
32                Steve McNair    2006              295         18.437500           468      29.250000             3050.0          190.625000               16          1.000000               12.0            0.750000               0.630342      1.333333
33                 Kurt Warner    2007              282         20.142857           452      32.285714             3409.0          243.500000               27          1.928571               17.0            1.214286               0.623894      1.588235
34              Anthony Wright    2005              164         20.500000           266      33.250000             1582.0          197.750000                6          0.750000                9.0            1.125000               0.616541      0.666667
35                Mike McMahon    2005               94         10.444444           207      23.000000             1158.0          128.666667                5          0.555556                8.0            0.888889               0.454106      0.625000
37                 Matt Schaub    2007              192         17.454545           289      26.272727             2241.0          203.727273                9          0.818182                9.0            0.818182               0.664360      1.000000
38                 Todd Bouman    2005               68         13.600000           122      24.400000              722.0          144.400000                2          0.400000                7.0            1.400000               0.557377      0.285714
40                 Marc Bulger    2005              192         24.000000           287      35.875000             2297.0          287.125000               14          1.750000                9.0            1.125000               0.668990      1.555556
41                   Jim Sorgi    2005               43          8.600000            62      12.400000              444.0           88.800000                3          0.600000                1.0            0.200000               0.693548      3.000000
42               Carson Palmer    2007              373         23.312500           575      35.937500             4130.0          258.125000               26          1.625000               20.0            1.250000               0.648696      1.300000
43                 Kyle Boller    2006               33          8.250000            55      13.750000              485.0          121.250000                5          1.250000                2.0            0.500000               0.600000      2.500000
45            Ryan Fitzpatrick    2005               76         19.000000           135      33.750000              777.0          194.250000                4          1.000000                8.0            2.000000               0.562963      0.500000
46                Brad Johnson    2006              270         18.000000           439      29.266667             2750.0          183.333333               10          0.666667               15.0            1.000000               0.615034      0.666667
47                 Eli Manning    2005              294         18.375000           558      34.875000             3762.0          235.125000               24          1.500000               17.0            1.062500               0.526882      1.411765
48                  Alex Smith    2005               84          9.333333           165      18.333333              875.0           97.222222                1          0.111111               11.0            1.222222               0.509091      0.090909
49                Steve McNair    2005              292         20.857143           476      34.000000             3161.0          225.785714               16          1.142857               11.0            0.785714               0.613445      1.454545
50               Kerry Collins    2005              302         20.133333           566      37.733333             3759.0          250.600000               20          1.333333               13.0            0.866667               0.533569      1.538462
51                  Tim Rattay    2005               56         14.000000            97      24.250000              667.0          166.750000                5          1.250000                6.0            1.500000               0.577320      0.833333
54              Peyton Manning    2007              337         21.062500           515      32.187500             4040.0          252.500000               31          1.937500               14.0            0.875000               0.654369      2.214286
55            Daunte Culpepper    2006               81         20.250000           134      33.500000              929.0          232.250000                2          0.500000                3.0            0.750000               0.604478      0.666667
56               Carson Palmer    2005              345         21.562500           509      31.812500             3836.0          239.750000               32          2.000000               12.0            0.750000               0.677800      2.666667
59                   Tony Romo    2007              335         20.937500           520      32.500000             4211.0          263.187500               36          2.250000               19.0            1.187500               0.644231      1.894737
62               Carson Palmer    2006              324         20.250000           520      32.500000             4036.0          252.250000               28          1.750000               13.0            0.812500               0.623077      2.153846
63              Byron Leftwich    2006              109         18.166667           184      30.666667             1158.0          193.000000                7          1.166667                5.0            0.833333               0.592391      1.400000
65                 Kyle Boller    2007              168         14.000000           275      22.916667             1743.0          145.250000                9          0.750000               10.0            0.833333               0.610909      0.900000
67                Chris Weinke    2006               56         18.666667            96      32.000000              625.0          208.333333                2          0.666667                4.0            1.333333               0.583333      0.500000
68              Peyton Manning    2005              305         19.062500           453      28.312500             3747.0          234.187500               28          1.750000               10.0            0.625000               0.673289      2.800000
70                Charlie Frye    2006              251         19.307692           391      30.076923             2449.0          188.384615               10          0.769231               17.0            1.307692               0.641944      0.588235
71              Sage Rosenfels    2007              154         17.111111           240      26.666667             1684.0          187.111111               15          1.666667               12.0            1.333333               0.641667      1.250000
72                  Drew Brees    2005              323         20.187500           500      31.250000             3576.0          223.500000               24          1.500000               15.0            0.937500               0.646000      1.600000
73                Todd Collins    2007               67         16.750000           105      26.250000              888.0          222.000000                5          1.250000                NaN            0.000000               0.638095           NaN
74             Joey Harrington    2005              188         15.666667           330      27.500000             2021.0          168.416667               12          1.000000               12.0            1.000000               0.569697      1.000000
75                 Chris Simms    2006               58         19.333333           106      35.333333              585.0          195.000000                1          0.333333                7.0            2.333333               0.547170      0.142857
76                  Jay Cutler    2006               81         16.200000           137      27.400000             1001.0          200.200000                9          1.800000                5.0            1.000000               0.591241      1.800000
77              Sage Rosenfels    2005               34          8.500000            61      15.250000              462.0          115.500000                4          1.000000                3.0            0.750000               0.557377      1.333333
81                   Mike Vick    2006              205         12.812500           389      24.312500             2474.0          154.625000               20          1.250000               13.0            0.812500               0.526992      1.538462
82                Drew Bledsoe    2005              300         18.750000           499      31.187500             3639.0          227.437500               23          1.437500               17.0            1.062500               0.601202      1.352941
83                 Trent Green    2006              121         15.125000           198      24.750000             1342.0          167.750000                7          0.875000                9.0            1.125000               0.611111      0.777778
84                  Alex Smith    2006              259         16.187500           443      27.687500             2901.0          181.312500               16          1.000000               15.0            0.937500               0.584650      1.066667
85                Trent Dilfer    2005              199         18.090909           333      30.272727             2321.0          211.000000               11          1.000000               12.0            1.090909               0.597598      0.916667
86            Daunte Culpepper    2005              139         19.857143           216      30.857143             1564.0          223.428571                6          0.857143               12.0            1.714286               0.643519      0.500000
88                   Tony Romo    2006              220         16.923077           337      25.923077             2903.0          223.307692               19          1.461538               13.0            1.000000               0.652819      1.461538
90                 A.J. Feeley    2007               59         19.666667           103      34.333333              681.0          227.000000                5          1.666667                8.0            2.666667               0.572816      0.625000
91                  David Carr    2006              302         18.875000           442      27.625000             2765.0          172.812500               11          0.687500               12.0            0.750000               0.683258      0.916667
93                 Josh McCown    2007              111         12.333333           191      21.222222             1151.0          127.888889               10          1.111111               11.0            1.222222               0.581152      0.909091
94                Rex Grossman    2007              122         15.250000           225      28.125000             1411.0          176.375000                4          0.500000                7.0            0.875000               0.542222      0.571429
95                Steve McNair    2007              133         22.166667           205      34.166667             1113.0          185.500000                2          0.333333                4.0            0.666667               0.648780      0.500000
98               David Garrard    2006              145         14.500000           241      24.100000             1735.0          173.500000               10          1.000000                9.0            0.900000               0.601660      1.111111
99            Vinny Testaverde    2007               94         13.428571           172      24.571429              936.0          133.714286                5          0.714286                6.0            0.857143               0.546512      0.833333
100                  Mike Vick    2005              214         14.266667           387      25.800000             2412.0          160.800000               15          1.000000               13.0            0.866667               0.552972      1.153846
101             Donovan McNabb    2005              211         23.444444           357      39.666667             2507.0          278.555556               16          1.777778                9.0            1.000000               0.591036      1.777778
102                  Jon Kitna    2007              355         22.187500           563      35.187500             4066.0          254.125000               18          1.125000               21.0            1.312500               0.630551      0.857143
104            Matt Hasselbeck    2006              210         17.500000           371      30.916667             2442.0          203.500000               18          1.500000               15.0            1.250000               0.566038      1.200000
107              Kerry Collins    2006               42         14.000000            90      30.000000              549.0          183.000000                1          0.333333                6.0            2.000000               0.466667      0.166667
109                Brett Favre    2005              372         23.250000           607      37.937500             3881.0          242.562500               20          1.250000               29.0            1.812500               0.612850      0.689655
110            Chad Pennington    2006              313         19.562500           485      30.312500             3352.0          209.500000               17          1.062500               16.0            1.000000               0.645361      1.062500

Now let's find the 40 player/season combinations with the highest completion percentage

In [23]:
nfl_result.sort_values(
    by = "completion_percentage",
    ascending = False
).head(40)

     player_display_name  season  completions_sum  completions_mean  attempts_sum  attempts_mean  passing_yards_sum  passing_yards_mean  passing_tds_sum  passing_tds_mean  interceptions_sum  interceptions_mean  completion_percentage  td_int_ratio
57        Anthony Wright    2006                3          1.500000             3       1.500000               31.0           15.500000                0          0.000000                NaN            0.000000               1.000000           NaN
330       Matt Gutierrez    2007                1          0.250000             1       0.250000               15.0            3.750000                0          0.000000                NaN            0.000000               1.000000           NaN
341       Matt Gutierrez    2009                1          1.000000             1       1.000000                3.0            3.000000                0          0.000000                NaN            0.000000               1.000000           NaN
347           Brad Smith    2009                1          0.090909             1       0.090909               27.0            2.454545                0          0.000000                NaN            0.000000               1.000000           NaN
422          Billy Volek    2010                1          0.333333             1       0.333333                8.0            2.666667                0          0.000000                NaN            0.000000               1.000000           NaN
474        Jordan Palmer    2010                3          3.000000             3       3.000000               18.0           18.000000                0          0.000000                NaN            0.000000               1.000000           NaN
479         Dennis Dixon    2008                1          1.000000             1       1.000000                3.0            3.000000                0          0.000000                NaN            0.000000               1.000000           NaN
538           Colt McCoy    2013                1          0.333333             1       0.333333               13.0            4.333333                0          0.000000                NaN            0.000000               1.000000           NaN
550         Tyrod Taylor    2011                1          0.500000             1       0.500000               18.0            9.000000                0          0.000000                NaN            0.000000               1.000000           NaN
563        Trent Edwards    2012                2          2.000000             2       2.000000               14.0           14.000000                0          0.000000                NaN            0.000000               1.000000           NaN
603         Chase Daniel    2012                1          1.000000             1       1.000000               10.0           10.000000                0          0.000000                NaN            0.000000               1.000000           NaN
605       Derek Anderson    2012                4          2.000000             4       2.000000               58.0           29.000000                0          0.000000                NaN            0.000000               1.000000           NaN
649          Brian Hoyer    2011                1          0.500000             1       0.500000               22.0           11.000000                0          0.000000                NaN            0.000000               1.000000           NaN
753     Tarvaris Jackson    2014                1          1.000000             1       1.000000                0.0            0.000000                0          0.000000                NaN            0.000000               1.000000           NaN
774        Scott Tolzien    2015                1          0.500000             1       0.500000                4.0            2.000000                0          0.000000                NaN            0.000000               1.000000           NaN
790           Matt Moore    2015                1          1.000000             1       1.000000               14.0           14.000000                0          0.000000                NaN            0.000000               1.000000           NaN
810         Chase Daniel    2015                2          1.000000             2       1.000000                4.0            2.000000                0          0.000000                NaN            0.000000               1.000000           NaN
841          Ryan Nassib    2015                5          5.000000             5       5.000000               68.0           68.000000                1          1.000000                NaN            0.000000               1.000000           NaN
883         Chase Daniel    2016                1          1.000000             1       1.000000               16.0           16.000000                0          0.000000                NaN            0.000000               1.000000           NaN
916          Alex Tanney    2019                1          1.000000             1       1.000000                1.0            1.000000                0          0.000000                NaN            0.000000               1.000000           NaN
923      Taylor Heinicke    2017                1          1.000000             1       1.000000               10.0           10.000000                0          0.000000                NaN            0.000000               1.000000           NaN
1097        Easton Stick    2020                1          1.000000             1       1.000000                4.0            4.000000                0          0.000000                NaN            0.000000               1.000000           NaN
1107       C.J. Beathard    2021                2          1.000000             2       1.000000               33.0           16.500000                0          0.000000                NaN            0.000000               1.000000           NaN
1203         AJ McCarron    2020                1          0.500000             1       0.500000               20.0           10.000000                0          0.000000                NaN            0.000000               1.000000           NaN
1412       Brandon Allen    2022                3          3.000000             3       3.000000               22.0           22.000000                0          0.000000                NaN            0.000000               1.000000           NaN
1415       Sean Clifford    2023                1          0.500000             1       0.500000               37.0           18.500000                0          0.000000                NaN            0.000000               1.000000           NaN
748         Mike Glennon    2016               10         10.000000            11      11.000000               75.0           75.000000                1          1.000000                NaN            0.000000               0.909091           NaN
546           Kyle Orton    2012                9          9.000000            10      10.000000               89.0           89.000000                1          1.000000                NaN            0.000000               0.900000           NaN
203           Jeff Blake    2005                8          4.000000             9       4.500000               55.0           27.500000                1          0.500000                NaN            0.000000               0.888889           NaN
225         Josh Johnson    2010               14          1.750000            16       2.000000              111.0           13.875000                0          0.000000                NaN            0.000000               0.875000           NaN
441           Quinn Gray    2008                7          7.000000             8       8.000000               76.0           76.000000                1          1.000000                NaN            0.000000               0.875000           NaN
879         Sean Mannion    2015                6          6.000000             7       7.000000               31.0           31.000000                0          0.000000                NaN            0.000000               0.857143           NaN
1360        Nick Mullens    2022               21          5.250000            25       6.250000              224.0           56.000000                1          0.250000                1.0            0.250000               0.840000           1.0
832       Kellen Clemens    2015                5          2.500000             6       3.000000               63.0           31.500000                1          0.500000                NaN            0.000000               0.833333           NaN
1428         Brian Hoyer    2022                5          5.000000             6       6.000000               37.0           37.000000                0          0.000000                NaN            0.000000               0.833333           NaN
1447          Mike White    2023                5          0.833333             6       1.000000               74.0           12.333333                1          0.166667                1.0            0.166667               0.833333           1.0
1033        Nate Sudfeld    2017               19         19.000000            23      23.000000              134.0          134.000000                0          0.000000                NaN            0.000000               0.826087           NaN
1050        Landry Jones    2017               23          7.666667            28       9.333333              239.0           79.666667                1          0.333333                1.0            0.333333               0.821429           1.0
728          Luke McCown    2015               32         16.000000            39      19.500000              335.0          167.500000                0          0.000000                1.0            0.500000               0.820513           0.0
1232         Brian Hoyer    2021                9          1.800000            11       2.200000              227.0           45.400000                1          0.200000                NaN            0.000000               0.818182           NaN

Lastly, we will find the 40 player/season combinations with the highest td_int_ratio

In [22]:
nfl_result.sort_values(
    by = "td_int_ratio",
    ascending = False
).head(40)

     player_display_name  season  completions_sum  completions_mean  attempts_sum  attempts_mean  passing_yards_sum  passing_yards_mean  passing_tds_sum  passing_tds_mean  interceptions_sum  interceptions_mean  completion_percentage  td_int_ratio
763            Tom Brady    2016              291         24.250000           432      36.000000             3554.0          296.166667               28          2.333333                2.0            0.166667               0.673611     14.000000
639           Nick Foles    2013              203         15.615385           317      24.384615             2891.0          222.384615               27          2.076923                2.0            0.153846               0.640379     13.500000
618          Josh McCown    2013              149         18.625000           224      28.000000             1829.0          228.625000               13          1.625000                1.0            0.125000               0.665179     13.000000
989        Aaron Rodgers    2018              372         23.250000           597      37.312500             4442.0          277.625000               25          1.562500                2.0            0.125000               0.623116     12.500000
200          Damon Huard    2006              148         14.800000           244      24.400000             1878.0          187.800000               11          1.100000                1.0            0.100000               0.606557     11.000000
1262       Aaron Rodgers    2020              372         23.250000           526      32.875000             4299.0          268.687500               48          3.000000                5.0            0.312500               0.707224      9.600000
1111       Aaron Rodgers    2021              366         22.875000           531      33.187500             4115.0          257.187500               37          2.312500                4.0            0.250000               0.689266      9.250000
286            Tom Brady    2010              324         20.250000           492      30.750000             3900.0          243.750000               36          2.250000                4.0            0.250000               0.658537      9.000000
20         Jake Delhomme    2007               55         18.333333            86      28.666667              617.0          205.666667                8          2.666667                1.0            0.333333               0.639535      8.000000
695        Aaron Rodgers    2014              341         21.312500           520      32.500000             4381.0          273.812500               38          2.375000                5.0            0.312500               0.655769      7.600000
662        Aaron Rodgers    2011              342         22.800000           501      33.400000             4636.0          309.066667               45          3.000000                6.0            0.400000               0.682635      7.500000
1057          Drew Brees    2019              281         25.545455           378      34.363636             2979.0          270.818182               27          2.454545                4.0            0.363636               0.743386      6.750000
1073       Aaron Rodgers    2019              353         22.062500           569      35.562500             4002.0          250.125000               26          1.625000                4.0            0.250000               0.620387      6.500000
953           Drew Brees    2018              364         24.266667           489      32.600000             3992.0          266.133333               32          2.133333                5.0            0.333333               0.744376      6.400000
1267     Patrick Mahomes    2020              390         26.000000           588      39.200000             4740.0          316.000000               38          2.533333                6.0            0.400000               0.663265      6.333333
145            Tom Brady    2007              398         24.875000           578      36.125000             4806.0          300.375000               50          3.125000                8.0            0.500000               0.688581      6.250000
951       Russell Wilson    2019              341         21.312500           516      32.250000             4110.0          256.875000               31          1.937500                5.0            0.312500               0.660853      6.200000
23         David Garrard    2007              208         17.333333           325      27.083333             2509.0          209.083333               18          1.500000                3.0            0.250000               0.640000      6.000000
418     Matthew Stafford    2010               57         14.250000            96      24.000000              535.0          133.750000                6          1.500000                1.0            0.250000               0.593750      6.000000
1168       Lamar Jackson    2019              265         17.666667           401      26.733333             3127.0          208.466667               36          2.400000                6.0            0.400000               0.660848      6.000000
1026        Dak Prescott    2016              311         19.437500           459      28.687500             3667.0          229.187500               23          1.437500                4.0            0.250000               0.677560      5.750000
766        Aaron Rodgers    2016              401         25.062500           610      38.125000             4428.0          276.750000               40          2.500000                7.0            0.437500               0.657377      5.714286
673       Peyton Manning    2013              450         28.125000           659      41.187500             5477.0          342.312500               55          3.437500               10.0            0.625000               0.682853      5.500000
872            Matt Ryan    2016              373         23.312500           534      33.375000             4944.0          309.000000               38          2.375000                7.0            0.437500               0.698502      5.428571
1038          Alex Smith    2017              341         22.733333           505      33.666667             4042.0          269.466667               26          1.733333                5.0            0.333333               0.675248      5.200000
1214     Patrick Mahomes    2019              319         22.785714           484      34.571429             4031.0          287.928571               26          1.857143                5.0            0.357143               0.659091      5.200000
742            Tom Brady    2015              402         25.125000           624      39.000000             4770.0          298.125000               36          2.250000                7.0            0.437500               0.644231      5.142857
180          Jeff Garcia    2006              116         14.500000           188      23.500000             1309.0          163.625000               10          1.250000                2.0            0.250000               0.617021      5.000000
928            Matt Ryan    2018              422         26.375000           608      38.000000             4924.0          307.750000               35          2.187500                7.0            0.437500               0.694079      5.000000
1067      Russell Wilson    2018              280         17.500000           427      26.687500             3448.0          215.500000               35          2.187500                7.0            0.437500               0.655738      5.000000
1115          Geno Smith    2021               65         16.250000            95      23.750000              702.0          175.500000                5          1.250000                1.0            0.250000               0.684211      5.000000
498        Aaron Rodgers    2012              371         23.187500           552      34.500000             4295.0          268.437500               39          2.437500                8.0            0.500000               0.672101      4.875000
1091      Ryan Tannehill    2020              315         19.687500           481      30.062500             3819.0          238.687500               34          2.125000                7.0            0.437500               0.654886      4.857143
293          Brett Favre    2009              364         22.750000           532      33.250000             4202.0          262.625000               33          2.062500                7.0            0.437500               0.684211      4.714286
962         Carson Wentz    2017              265         20.384615           440      33.846154             3296.0          253.538462               33          2.538462                7.0            0.538462               0.602273      4.714286
1088      Deshaun Watson    2020              382         23.875000           544      34.000000             4823.0          301.437500               33          2.062500                7.0            0.437500               0.702206      4.714286
1189        Kirk Cousins    2021              372         23.250000           561      35.062500             4221.0          263.812500               33          2.062500                7.0            0.437500               0.663102      4.714286
903           Derek Carr    2016              357         23.800000           560      37.333333             3937.0          262.466667               28          1.866667                6.0            0.400000               0.637500      4.666667
1252      Jameis Winston    2021               95         13.571429           161      23.000000             1170.0          167.142857               14          2.000000                3.0            0.428571               0.590062      4.666667
1300         C.J. Stroud    2023              319         21.266667           499      33.266667             4108.0          273.866667               23          1.533333                5.0            0.333333               0.639279      4.600000